### ISSUE TITLE
Helper does not work with htmlbars

### ISSUE THREAD

**Issue by kategengler** [kategengler/ember-feature-flags#10]
Ember helpers no longer support blocks w/ htmlbars enabled. This addon will currently prevent your app from working in greater than Ember 1.10 beta. 

A potential resolution is to remove the helper. It was nice to make flag use obvious in templates, but since `features` is injected on all components and controllers, it should be fine to use in a plain `if`, if we make each flag a defined property on features. 

A potential downside is that this would restrict the naming of the flags, previously, they could be any string. 

Old way:
```hbs
{{#if-feature 'new-feature'}}
   <div>Something</div>
{{else}}
  <div>Else</div>
{{/if-feature}}
```

New way:
```hbs
{{#if features.newFeature}}
  <div>Something</div>
{{else}}
  <div>Else</div>
{{/if}}
```

An alternative would be to write a new helper that would resemble the previous helper, be bound and make use of the existing `if` helper internally. I think this is preferred and can build off the work in #5

**Comment by Globegitter** [comment]
I just removed the if helper to make it compatible with HTMLBars https://github.com/Globegitter/ember-feature-flags in case anyone needs something working right now :)
