### ISSUE TITLE
Discussion - support for numeric feature values

### ISSUE THREAD

**Issue by slindberg** [kategengler/ember-feature-flags#16]
The app I work on has features that can be enabled/disabled, but also has feature 'limits' (think Slack's "You have 4 more integrations available..."). This would require passing feature values straight through without the boolean cast, and also possibly some type sniffing for things like numbers encoded as strings.

The only way I can see it breaking backwards compatibility is if someone is doing something like:

```js
// This might happen if features are set through environment variables
this.features.enable('foo', '1');

// A bit contrived, but still valid
if (this.features.get('foo') === true) {
  // ...
}
```

I could keep the default behavior of casting to a boolean by hiding this behind an opt-in config setting, e.g. `featureFlagsNumericValues`.

The readability of `this.features.enable('integration-limit', 5)` suffers a little too, but not too badly IMO.

I realize this kind of goes against the name of the entire project, so is this something you'd be open to supporting? If so, I'll get to work on a PR :smile:

**Comment by kategengler** [comment]
I think this is outside the scope of the project. It's really intended to be feature flags for development purposes (toggling features per environment or per user until they are ready for full release), not for use as actual business logic, though I suppose it could be used that way. 

I think this would be a good use case of something like https://github.com/minutebase/ember-can

**Comment by slindberg** [comment]
Fair enough, I'll look into ember-can, thanks.
