### ISSUE TITLE
ember-feature-flags-flip

### ISSUE THREAD

**Issue by jkatsnelson** [kategengler/ember-feature-flags#21]
I am going to build ember-feature-flags-flip -- The goal is to make it possible to toggle feature flags from within the app itself. I'll probably start with something like:

`window.flipFlag('new-homepage')`

Let me know if you have any input or thoughts! Thanks!

**Comment by kategengler** [comment]
We spoke offline, but for documentation sake, if you wanted to have a UI within an app that toggled feature flags, all you would need to do is toggle the flag in an action using the service:

```js
actions: {
  toggleFlag: function(flagName) {
    if(this.features.isEnabled(flagName){
      this.features.disable(flagName);
    }
    else {
      this.features.enable(flagName);
    }
  }
}
```
