### ISSUE TITLE
Access to features in a custom Adapter or Serializer

### ISSUE THREAD

**Issue by elidupuis** [kategengler/ember-feature-flags#26]
Is there a simple way to get access to `this.features` inside an Ember Data Adapter or Serializer? We're reworking some API stuff and that would be really useful :wink:

**Comment by elidupuis** [comment]
This seems to work, I'm just wondering if you suggest another approach...

```js
// app/initializers/custom-feature-flags.js
import config from '../config/environment';

export function initialize(registry, application) {
  var serviceName = config.featureFlagsService || 'features';
  application.inject('adapter', serviceName, 'features:-main');
}

export default {
  name: 'feature-flags',
  initialize: initialize,
  after: 'ember-feature-flags'
};
```

**Comment by kategengler** [comment]
It will now be a standard Ember service, so you should be able to get at it with `Ember.inject.service('features')`
