### ISSUE TITLE
setup does not call notifyPropertyChange

### ISSUE THREAD

**Issue by ecksun** [kategengler/ember-feature-flags#29]
I'm fetching all enabled features from my backend and would thus like to do:

```
this.features.setup(this.model.get('features'));
```

However this does not re-render my templates where I have used the toggles as `notifyPropertyChange` isn't called from within `setup()`.

Perhaps this is per design, in which case I would suggest updating the documentation to reflect that.

**Comment by kategengler** [comment]
This was the original intention, because originally flags weren't properties (that came in as PR). That said, it will now notifyPropertyChange on setup.
