### ISSUE TITLE
LOG_FEATURE_FLAG_MISS not logging

### ISSUE THREAD

**Issue by RyanHirsch** [kategengler/ember-feature-flags#30]
When setting `ENV.LOG_FEATURE_FLAG_MISS = true;` I am not seeing the logging of the miss. Looking through the `logFeatureFlagMissEnabled()` it assumes that `.ENV` is off of the window object and by default it is not.

I was able to get logging of misses to work by manually attaching `.ENV` to the window object, but that doesn't seem to be the 'right' solution,

I am on ember 1.13.10.

**Comment by kategengler** [comment]
Should be fixed on master now, soon to be released. Thanks for reporting the bug and sorry that I took so long to get to it.
