### ISSUE TITLE
Best practice for API based feature flags

### ISSUE THREAD

**Issue by offirgolan** [kategengler/ember-feature-flags#33]
I was wondering if there are any docs or examples on best practices/usage when it comes to using this addon with API based feature flags. These APIs are mostly based on user permission as well as the environment.

**Comment by utilityboy** [comment]
@offirgolan have you had any luck figuring this out?

**Comment by offirgolan** [comment]
@utilityboy I ended up using [ember-cli-inject-meta](https://github.com/offirgolan/ember-cli-inject-meta) which I use to make API calls, create a module / service and use that to define my feature flags.

**Comment by utilityboy** [comment]
@offirgolan cool!  I'll take a look at that if my approach goes sideways.  Thanks!

**Comment by offirgolan** [comment]
@utilityboy np! Good luck 😺

**Comment by kategengler** [comment]
This has since been documented in the README
