### ISSUE TITLE
export features as standard ember service

### ISSUE THREAD

**Issue by wireframe** [kategengler/ember-feature-flags#34]
trying to inject the `features` service into other components using `Ember.inject.service()` raises an error:
```javascript
export default Ember.Component.extend({
  features: Ember.inject.service()
});
```
> Uncaught Error: Attempting to inject an unknown injection: `service:features`

**Comment by jcope2013** [comment]
it is already injected into components so no need to list it

https://github.com/kategengler/ember-feature-flags/blob/master/app/initializers/ember-feature-flags.js#L9

**Comment by wireframe** [comment]
correct.  my example should have been for an ember service.  I'm not able to inject the `features` service into another service which should be possible with ember's built in dependency injection.

**Comment by acorncom** [comment]
I'd love to see this as well.  We're looking up the features service in the container in an instance initializer and would prefer to not be relying on a private lookup:

`appInstance.container.lookup('features:-main')`

**Comment by jamesarosen** [comment]
As a workaround, what about
```js
// app/instance-initializers/ember-feature-flags-service.js
export default {
  name: 'ember-feature-flags-service',

  initialize({ registry }) {
    const features = registry.lookup('features:-main');
    registry.register('service:features', features, { singleton: true, instantiate: false });
  }
};
```

**Comment by kategengler** [comment]
I've now made it a standard service (committed to master, to be released soon), but it will be a breaking change.
