### ISSUE TITLE
[Feature Request] Use flags in custom Adapter

### ISSUE THREAD

**Issue by bpinel** [kategengler/ember-feature-flags#42]
Perhaps I miss something, but Feature flags seems to be usable only in routers, controlers and templates.
It would be great to be able to use them in Adapters. 
I there a way to make this possible ?

**Comment by bpinel** [comment]
I just added a new inject in ember-feature-flags.js to do the job
  application.inject('adapter', serviceName, 'features:-main');
Is there a reason you limit this injection to router, controller and component ?
Anyway, thank you for your add ins to Ember.

**Comment by kategengler** [comment]
You can add your own injections by making your own initializer:


To inject into all adapters: (using >= 3.0 of ember-feature-flags)
```
$ ember g initializer add-ember-feature-flags-to-adapters

// app/initializers/add-ember-feature-flags-to-adapters.js

import config from '../config/environment';

export function initialize() {
  let application = arguments[1] || arguments[0]; // depends on your version of Ember
  let serviceName = config.featureFlagsService || 'features'; 
  let serviceLookupName = `service:${serviceName}`;
  application.inject('adapter', serviceName, serviceLookupName);
}

export default {
  name: 'add-ember-feature-flags-to-adapters',
  after: 'emberFeatureFlags',
  initialize
};

//
alternatively, in your adapter you can use:

features: inject.service()
```

I'm not sure about expanding the default injections. In fact, I've been exploring not injecting the service anywhere by default and relying on the users to do `inject.service` where it is needed. The only thing that stopped me from doing this with 3.0 is the desire to deprecate the functionality before breaking, the fact that the injection name is customizable and a desire to make using feature flags as low overhead as possible for end developers, especially in templates.
