### ISSUE TITLE
`withFeature` Instructions Appear to be Incorrect

### ISSUE THREAD

**Issue by jherdman** [kategengler/ember-feature-flags#44]
When attempting to following the instructions provided for including the `withFeature` helper into my acceptance tests, I see the following error:

```
Uncaught Error: Could not find module `ember-feature-flags/tests/helpers/with-feature` imported from `my-app/tests/test-helper`
```

Instead the following worked:

```js
// in tests/test-helper.js
import './helpers/with-feature';
```

Am I doing something wrong, or does the README need to be updated? I'm more than happy to provide a patch should the latter be true.

**Comment by kategengler** [comment]
Readme has been updated. Sorry about this!
