### ISSUE TITLE
Expose _flags as a public API

### ISSUE THREAD

**Issue by willrax** [kategengler/ember-feature-flags#53]
Hi,

I was wondering if you would be open to making the _flags API public? We were hoping to get a list of all the flags that are currently available in our app so we can toggle them. I'm more than happy to pull the PR together if you are 😄

**Comment by jonnii** [comment]
@willrax a work around for this is doing something like this:

```
import Ember from 'ember';
import ENV from '../config/environment';

export default Ember.Controller.extend({
  flagNames: Ember.computed(function() {
    return Ember.A(Object.keys(ENV.featureFlags));
  })
});
```

You can then do the following in your template:

```
{{#each flagNames as |flag|}}
  {{flag}} - {{get features flag}}<br/>
{{/each}}
```

**Comment by kategengler** [comment]
I'd be happy to have a computed property or method that returns a list of flags. I don't want to directly expose the _flags object so that we can change how we internally store flags, if necessary.
