### ISSUE TITLE
Introduce feature-flag template helper

### ISSUE THREAD

**Issue by SergeAstapov** [kategengler/ember-feature-flags#65]
Introduce a template helper `feature-flag` that can be used to conditionally render some content:
```
# templates/my-component.hbs
{{#if (feature-flag 'newHomepage')}}
  {{link-to "new.homepage"}}
{{else}}
  {{link-to "old.homepage"}}
{{/if}}
```

This can be achieved today with `features` service but it requires you to inject the service to a component:
```
# templates/my-component.hbs
{{#if features.newHomepage)}}
  {{link-to "new.homepage"}}
{{else}}
  {{link-to "old.homepage"}}
{{/if}}

# component/my-component.js
export default Component.extend({
  features: service()
});
```

Also it would not be possible to use that addon with template only component once [RFC #278](https://github.com/emberjs/rfcs/pull/278) lands.

**Comment by SergeAstapov** [comment]
@kategengler would it make sense/be possible to refactor `withFeature` test helper to work with newish rendering tests?
Question inspired by https://dockyard.com/blog/2018/01/18/test-helpers-the-next-generation

**Comment by kategengler** [comment]
@SergeAstapov Definitely. In fact, the example in the RFC is for `withFeature` https://github.com/emberjs/rfcs/blob/master/text/0268-acceptance-testing-refactor.md#test-helper

**Comment by SergeAstapov** [comment]
Nice! Even better!

@kategengler If everything looks good I'll work on this and submit a PR
