### ISSUE TITLE
[Question] `feature-flag` helper not CP aware?

### ISSUE THREAD

**Issue by walter** [kategengler/ember-feature-flags#72]
While working on some acceptance/application tests, I noticed that this form of feature detection will update when a feature is disabled at runtime:

```JavaScript
{{#if features.featureName}}
...functionality
{{/if}}
```

However if I use the`feature-flag` helper, disabling the feature at runtime will not trigger an update to this conditional:

```JavaScript
{{#if (feature-flag 'featureName')}}
...functionality
{{/if}}
```

Is this expected behavior? If so it might be worth mentioning in the `README`.

This is in Ember 2.18.2 and with ember-feature-flags 5.0.

**Comment by kategengler** [comment]
This is not expected. The helper should recompute when the flag changes. 

This code is intending to do that: https://github.com/kategengler/ember-feature-flags/blob/master/addon/helpers/feature-flag.js#L14

And here is the test for it: https://github.com/kategengler/ember-feature-flags/blob/master/tests/integration/helpers/feature-flag-test.js#L55

Could you help debug this? Maybe add an acceptance test for it?

**Comment by kategengler** [comment]
Closing this as it is working in my own apps.
