### ISSUE TITLE
Errors in integration tests in ember 3.1.0

### ISSUE THREAD

**Issue by Sinled** [kategengler/ember-feature-flags#73]
Hi, at first thanks for great addon, 

but i have small problem with it, after i've updated application to ember 3.1 version
my integration tests started failing with error 
```
Assertion Failed: You attempted to access the `didRemoveListener` property (of <app@service:features::ember601>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('didRemoveListener')` in this case.
```

i couldn't find such code in this addon, so i tried to run `ember-feature-flags` tests and they do fail if you change ember version to 3.1

Is there any way to solve this problem?

**Comment by kategengler** [comment]
I think you may be running into what is fixed by this PR to `ember.js` https://github.com/emberjs/ember.js/pull/16404

I'm not sure this has anything to do with this addon.

**Comment by Sinled** [comment]
Yes, that pr fixes my problem, thanks.
