### ISSUE TITLE
contextual featureFlags

### ISSUE THREAD

**Issue by basz** [kategengler/ember-feature-flags#74]
Hi,

I'm wondering if I could use this add-on for the following use case

I need a particular 'feature' to enabled based on the context in which it is 'asked'. Meaning a form should only show and validate and submit some fields depending on the model. (creation date).

So to be able to ask the following

```
{{#if feature.enableNewFormElements model}}
   ... // render additional element
```
and
```
if( this.get('feature').isEnabled(model)}}
   ... // validate and submit additional element
```

I would need to be able to something, like;

```
this.get('feature').set('enableNewFormElements', function(model) {
    return moment(model('inceptionDate')).isAfter(moment('2018-04-12'), 'day');
})
```

I don't believe this is possible at this time. But would you consider it a good addition?

As a work around I can simply enable/disable when the component initialises. Much like I'm doing at the moment based on feature flags for the currentUser. But then again I could also use a simple computed property for that. 

edit. a simple `this.get('feature').set({'enableNewFormElements': true})`, like setUp works but then without a reset, would be a simple but powerful addition.

**Comment by kategengler** [comment]
Hi, 

This addon is meant to provide feature toggles as a development tool, but your use case sounds like business logic. Why not create your own service and helpers?

**Comment by basz** [comment]
I came to the same conclusion. Thanks
