### ISSUE TITLE
Release Possible?

### ISSUE THREAD

**Issue by jherdman** [kategengler/ember-feature-flags#85]
Hi friends!

Is it possible to cut a releasing containing 06b33fd5d6e78538c8611cdf134e93adc3a04e71? It'd be super nice to silence the "volatile" deprecation warning.

<3

**Comment by SergeAstapov** [comment]
Just came here to post exactly the same comment, but its already there.

**Comment by kategengler** [comment]
Hi! It's definitely on my list, but unlikely to happen before the weekend.

**Comment by harrywebdev** [comment]
Hi @kategengler would you be so kind and release it? 🙏🏻

**Comment by kategengler** [comment]
v6.0.0 is deployed (breaking change due to dropped Node version support < 8). Sorry for the absurdly long delay!
